### ISSUE TITLE
coveralls should read any file that starts with .coverage

### ISSUE THREAD

**Issue by thedrow** [coagulant/coveralls-python#25]
Currently coverage generates coverage data files to .coverage.* format.
coveralls-python only reads files named .coverage.

**Comment by jessamynsmith** [comment]
I don't know what version of coverage this was, but I think this issue is stale at this point. Coverage 3.x and 4.x both create .coverage files.

**Comment by coagulant** [comment]
@jessamynsmith good point.

Closing this. Feel free to reopen, if one provides a case when we need to parse more files than we do now.

**Comment by radiac** [comment]
I think this occurs when coverage is called with the ``-p`` option - that will create coverage files with unique suffixes so you can combine them later (see [coverage docs](http://nedbatchelder.com/code/coverage/cmd.html#h_combining_data_files)).

Perhaps I was missing something obvious, but I ran into this when trying to have tox locally combine coverage across multiple environments (using coverage 4.0a5), but still wanting coveralls to find them all when run on travis ci. I found though that you can achieve the same thing by removing the ``-p`` option and manually specifying the suffix with an env var in the tox base environment:

    [testenv]
    setenv = COVERAGE_FILE=.coverage.{envname}
    ...

Because coveralls uses coverage to find the file, as long as it's run in the same env that generates the coverage report, it will also respect the env var and find the file in a travis instance. When run locally, the coverage files will still have unique names, so can be combined later with ``coverage combine``. For a more detailed example, my working ``tox.ini`` is [here](https://github.com/radiac/django-tagulous/blob/master/tox.ini).

Since this issue has so little activity, either I'm doing something wrong, or this seems to be fairly uncommon usage - either way it doesn't seem worth reopening and modifying code, but perhaps this comment will help others.
