### ISSUE TITLE
Hits per line

### ISSUE THREAD

**Issue by myint** [coagulant/coveralls-python#3]
I noticed that the line coverage result is binary (0 or 1) even if [branch coverage](http://nedbatchelder.com/code/coverage/branch.html) is enabled. Is there any reason for not incrementing the number of hits for lines that are covered by more than one branch?

Of course this is not an exact mapping to the hits per line that Coveralls wants. But it seems better to me than a strict binary hit status (which shows less information than Ned's [HTML reports](http://nedbatchelder.com/code/coverage/sample_html/cogapp_cogapp.html)).

**Comment by coagulant** [comment]
Feel free to reopen when and if branch coverage will be available on coveralls

**Comment by xanderdunn** [comment]
I find this feature useful in my C++ project because it gives me a good idea of how well a given line of code is actually tested.  If the line of code is run only once, then I know there is only one test that executes it and this is suboptimal test coverage.  If a line of code is run 24,000 times, then I know we've got far better testing of it (It's probably safe to assume that the tests aren't calling the exact same thing many times over).

**Comment by ThePadawan** [comment]
@coagulant Coveralls now supports Branch Coverage and counts hits per line.
Could you reopen this issue?
