### ISSUE TITLE
No files reported on Travis

### ISSUE THREAD

**Issue by meatballs** [coagulant/coveralls-python#75]
My Travis build is reporting 0 files when I use `coveralls debug` There's an example at the bottom of this build:

https://travis-ci.org/Axelrod-Python/Axelrod/builds/62563230

When I run the same coverage command locally, followed by `coveralls debug` I get the expected results and I can even run `coveralls` successfully. The result of a local run is job number 511 here:

https://coveralls.io/r/Axelrod-Python/Axelrod

The only difference between the two is that I created `.coveralls.yml` for my local test and entered my `repo_token` but my understanding was that I don't need to do that for a Travis build.

Am I missing something somewhere?

**Comment by coagulant** [comment]
I think coveralls can't find coverage data because it was executed from [docs folder](https://github.com/Axelrod-Python/Axelrod/commit/8a88a5c8c27054a29dddb755628dbdafc3bcc15c#diff-354f30a63fb0907d4ad57269548329e3R12).

I suggest coveralls should exit with non-zero status and output error in stderror if coveralls gathers no coverage files. This will help identify problem with empty coverage right away.

Something like this:
```
$ coveralls
Error: No .coverage files found. Please make sure you've run coverage from current directory.
```

What do you think, @jessamynsmith?

**Comment by meatballs** [comment]
Aggghhhh!! Many thanks indeed for pointing out something so damned obvious!!

**Comment by jessamynsmith** [comment]
I think that sounds very reasonable, @coagulant. I am always a fan of clear output. :)
