### ISSUE TITLE
AppVeyor not supported?

### ISSUE THREAD

**Issue by ionelmc** [coagulant/coveralls-python#86]
Seems just running `coveralls` don't work as is on AppVeyor. Eg: https://ci.appveyor.com/project/ionelmc/pytest-benchmark/build/master-165/job/1qn8ikvoxw6bn8qn#L214

I don't know what going on here - is this a lacking feature in coveralls-python or Coveralls don't support this at all?

**Comment by coagulant** [comment]
AppVeyor is like any other CI needs coveralls token to work: https://github.com/coagulant/coveralls-python#usage-another-ci  Except Travis, which has special integration, that does not require token.

Error message is misleading, we have to fix it, but it mentions the problem:
https://ci.appveyor.com/project/ionelmc/pytest-benchmark/build/master-165/job/1qn8ikvoxw6bn8qn#L214

**Comment by ionelmc** [comment]
I know I can fix it with env vars but I don't want to to it for all the projects 😒

How does Codecov do it? It seems to work out of the box on appveyor.

**Comment by coagulant** [comment]
Coveralls says they repo token is required for API calls https://coveralls.zendesk.com/hc/en-us/articles/201350799-API-Reference
But for Travis CI we do not send it, `service_name` and `service_job_id` is enough: https://github.com/coagulant/coveralls-python/blob/master/coveralls/api.py#L51

I suppose AppVeyor might have gained token-free support since 2013, but I don't know that. Might as well check official ruby coveralls gem to check if that's true )

**Comment by ionelmc** [comment]
Looks like they got something to work: https://github.com/lemurheavy/coveralls-public/issues/429

**Comment by rbcarson** [comment]
I'm pleased to confirm that this library works with AppVeyor - I just tried it and the log is available [here](https://ci.appveyor.com/project/rbcarson/pypac/build/0.1.0.13/job/g0bl5yiujk0s6a56). The coveralls token still needs to be provided, but that's fairly easy. #111 improves the message.

While `coveralls-python` works, `python-coveralls` doesn't work because of its dependency on the `sh` library, which isn't available for Windows: see z4r/python-coveralls/issues/26.

**Comment by coagulant** [comment]
@rbcarson thank you. Originally we were also using sh, but removed it in #36
